### ISSUE TITLE
API Gateway: Secret name is hard-coded in values.yaml

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-helm-charts#15]
```
  # -- secret for elasticsearch user. Will need to adjust the secret's name. By default the secret name is <releasename>-apigateway-sag-user-es.
  # Adjust accordingly if your release name is different. 
  extraEnvSecrets:
    ES_PASSWORD:
      secret: apigw-apigateway-sag-user-es
      key: password
    ES_USER:
      secret: apigw-apigateway-sag-user-es
      key: username
```

Isn't it possible to express the secret name dynamically based on the release name? Otherwise the user has to overwrite this value for every new release.
