### ISSUE TITLE
API Gateway: How to configure multiple Kibana instances?

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-helm-charts#37]
It seems the count is hard-coded to 1:

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  {{- if .Values.kibana.image }}
  image: {{ .Values.kibana.image }}
  {{- end }}
  version: {{ .Values.kibana.version }}
  count: 1
```

Can we pull this from a value?
